project:
  name: Veyon
  version: 4.0.92
  copyright: 2004-2018
  author: Tobias Junghans
  contact: Tobias Junghans <tobydox@veyon.io>
  contributors:
    - Tobias Junghans <tobydox@veyon.io>
  description: Virtual Eye On Networks - OpenSource classroom management
  license: GPL-2.0
  category: Education
  homepage: http://veyon.io
  repository:
    type: git
    url: https://github.com/veyon/veyon.git
  bugs:
    url: https://github.com/veyon/veyon/issues
  documentation:
    url: http://docs.veyon.io
